/**********************************************************************
*    optAsm v1.0                                                      *
*    Developer:   Max I. Belyaev        (uncleglitch@gmail.com)       *
*    Idea:        Andrey S. Miroshnikov (mirandrey@mail.ru)           *
*    Copyright by Andrey S. Miroshnikov and Max I. Belyaev, 2011-2013 *
**********************************************************************/

#ifndef SERVICES_TYPES_H
#define SERVICES_TYPES_H

enum SourceStringType {LABEL_GLOBAL,
                      LABEL_LOCAL,
                      LABEL_UNNAMED,
                      DATA_SINGLE,
                      DATA_DUP,
                      COMMENT,
                      OPCODE_MOV,
                      OPCODE_XCHG,
                      OPCODE_XLAT,
                      OPCODE_LEA,
                      OPCODE_LDS,
                      OPCODE_LES,
                      OPCODE_LAHF,
                      OPCODE_SAHF,
                      OPCODE_PUSH,
                      OPCODE_POP,
                      OPCODE_PUSHF,
                      OPCODE_POPF,
                      OPCODE_IN,
                      OPCODE_OUT,
                      OPCODE_ADD,
                      OPCODE_ADC,
                      OPCODE_SUB,
                      OPCODE_SBB,
                      OPCODE_CMP,
                      OPCODE_MUL,
                      OPCODE_IMUL,
                      OPCODE_DIV,
                      OPCODE_IDIV,
                      OPCODE_INC,
                      OPCODE_DEC,
                      OPCODE_NEG,
                      OPCODE_CBW,
                      OPCODE_CWD,
                      OPCODE_DAA,
                      OPCODE_DAS,
                      OPCODE_AAA,
                      OPCODE_AAS,
                      OPCODE_AAM,
                      OPCODE_AAD,
                      OPCODE_BT,
                      OPCODE_BTC,
                      OPCODE_BTR,
                      OPCODE_BTS,
                      OPCODE_AND,
                      OPCODE_OR,
                      OPCODE_XOR,
                      OPCODE_TEST,
                      OPCODE_NOT,
                      OPCODE_RCL,
                      OPCODE_RCR,
                      OPCODE_ROL,
                      OPCODE_ROR,
                      OPCODE_SAL,
                      OPCODE_SAR,
                      OPCODE_SHL,
                      OPCODE_SHR,
//                      OPCODE_REP_MOVS,
//                      OPCODE_REP_STOS,
//                      OPCODE_REPE_CMPS,
//                      OPCODE_REPE_SCAS,
//                      OPCODE_REPZ_CMPS,
//                      OPCODE_REPZ_SCAS,
//                      OPCODE_REPNE_MOVS,
//                      OPCODE_REPNE_STOS,
//                      OPCODE_REPNZ_CMPS,
//                      OPCODE_REPNZ_SCAS,//
                      OPCODE_JMP,
                      OPCODE_CALL,
                      OPCODE_RET,
                      OPCODE_JL,
                      OPCODE_JNGE,
                      OPCODE_JNL,
                      OPCODE_JGE,
                      OPCODE_JLE,
                      OPCODE_JNG,
                      OPCODE_JNLE,
                      OPCODE_JG,
                      OPCODE_JB,
                      OPCODE_JNAE,
                      OPCODE_JC,
                      OPCODE_JBE,
                      OPCODE_JNA,
                      OPCODE_JNB,
                      OPCODE_JAE,
                      OPCODE_JNC,
                      OPCODE_JNBE,
                      OPCODE_JA,
                      OPCODE_JE,
                      OPCODE_JZ,
                      OPCODE_JP,
                      OPCODE_JPE,
                      OPCODE_JO,
                      OPCODE_JS,
                      OPCODE_JNE,
                      OPCODE_JNZ,
                      OPCODE_JNP,
                      OPCODE_JPO,
                      OPCODE_JNO,
                      OPCODE_JNS,
                      OPCODE_JCXZ,
                      OPCODE_LOOP,
                      OPCODE_LOOPE,
                      OPCODE_LOOPZ,
                      OPCODE_LOOPNE,
                      OPCODE_LOOPNZ,
                      OPCODE_INT,
                      OPCODE_INTO,
                      OPCODE_CLC,
                      OPCODE_STC,
                      OPCODE_CMC,
                      OPCODE_CLD,
                      OPCODE_STD,
                      OPCODE_CLI,
                      OPCODE_STI,
                      OPCODE_HLT,
                      OPCODE_WAIT,
                      OPCODE_LOCK,
                      OPCODE_ESC,
                      OPCODE_NOP};

enum OperandType{MEMORY,
                 ACCUMULATOR,
                 BASE_REGISTER,
                 BASE_REGISTER_WITHOUT_ACCUMULATOR,
                 SEGMENT_REGISTER_WITHOUT_CS,
                 SEGMENT_REGISTER,
                 CONSTANT_VALUE};

#endif // SERVICES_TYPES_H
